# Generated by Django 4.1.5 on 2023-01-14 19:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('trip_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trip_start_time', models.DateTimeField()),
                ('trip_end_time', models.DateTimeField()),
                ('trip_start_station_name', models.CharField(max_length=100)),
                ('trip_end_station_name', models.CharField(max_length=100)),
                ('trip_title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TripDetails',
            fields=[
                ('trip_details_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trip_details_time', models.DateTimeField()),
                ('trip_details_location_to_visit', models.CharField(max_length=100)),
                ('trip_location_budget', models.IntegerField()),
                ('trip_members', models.IntegerField()),
                ('trip_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tripBackend.trip')),
            ],
        ),
    ]
