# Generated by Django 4.1.5 on 2023-01-15 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tripBackend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripdetails',
            name='trip_details_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
