# Generated by Django 4.1.5 on 2023-01-15 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tripBackend', '0002_alter_tripdetails_trip_details_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripdetails',
            name='trip_location_budget',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tripdetails',
            name='trip_members',
            field=models.CharField(max_length=100),
        ),
    ]
